### PR TITLE
Fix/commit scans

### LINKED ISSUE #134: File paths are not respected in deep commit scans
If a file is moved to a different path within the repo in a later commit it will not be searched in the earlier commits. Wraith will throw a file not found error because it is not fetching the commits, it is simply scanning them based on the file list from the top level commit.

### LINKED ISSUE #138: Only the current file is being scanned, no matter the commit depth
Only the current file is being scanned, no matter the commit depth

### PR DESCRIPTION
**Pull request by shreyas-sriram**
Addresses https://github.com/N0MoreSecr3ts/wraith/issues/134 and https://github.com/N0MoreSecr3ts/wraith/issues/138.

> @mattyjones I am not aware of all the issues related to this, feel free to add them if I have missed any.

Logic for `case PartContent` in `func (s PatternSignature) ExtractMatch(..)` is updated to handle **non-locaPath scanType**. The code snippet was correct, but the flow of execution was wrong. This has been fixed.

In `io.go`, the execution is meant to continue even if the file does not exist in the filesystem. What happens otherwise (before this) is, wraith doesn't see the file in the filesystem for git scans and ignores the file.

> The reasoning for this is difficult to understand, hence I have added it in code as comments.

# Sample Output
Running wraith against https://github.com/shreyas-sriram/git-with-secrets.

## Before
```
--------Results--------

-------Findings------
Total Findings......: 1

--------Files--------
Total Files.........: 5
Files Scanned.......: 1
Files Ignored.......: 4
Files Dirty.........: 1

---------SCM---------
Repos Found.........: 0
Repos Cloned........: 2
Repos Scanned.......: 1
Commits Total.......: 5
Commits Scanned.....: 5
Commits Dirty.......: 1

-------General-------
Wraith Version......: 0.0.9
Signatures Version..: 0.0.1
Elapsed Time........: 21.168165ms
```

## After
```
--------Results--------

-------Findings------
Total Findings......: 5

--------Files--------
Total Files.........: 5
Files Scanned.......: 5
Files Ignored.......: 0
Files Dirty.........: 5

---------SCM---------
Repos Found.........: 0
Repos Cloned........: 2
Repos Scanned.......: 1
Commits Total.......: 5
Commits Scanned.....: 5
Commits Dirty.......: 4

-------General-------
Wraith Version......: 0.0.9
Signatures Version..: 0.0.1
Elapsed Time........: 23.804434ms
```

### CODE REVIEW

**Comment by shreyas-sriram** [comment]
Another thing I noticed is that the first (oldest) commit is never scanned.

Output from `--debug` mentions that there are 0 changes in the first commit.
```
0 changes in b86a81ffe21f40e5186cd0f3da3e4d90fee40a73
```

This can also be seen in the PR's sample output (https://github.com/N0MoreSecr3ts/wraith/pull/139#issue-1353195555) under `Commits Dirty.......: 4`. The expected number of dirty commits is 5.

**Comment by mattyjones** [comment]
This is great I will review it this week coming up. The first commit is never scanned possibly because it is root. It may not be able to go back as git might not be able, as it currently stands, to pull changes as there are no changes to pull being the absolute commit.

@shreyas-sriram

File: core/io.go [hunk 1]
```diff
@@ -102,8 +102,18 @@ func IsMaxFileSize(filename string, sess *Session) (bool, string) {
...
-		return true, "does not exist"
+	// This error occurs when the file is not found.
+	// The source of truth for files traversed comes from:
+	// 		git - the commit history (or)
+	// 		filepath - walking the filepath.
+	//
+	// In the case of filepath, it can be safely assumed that the file will always exist because we only check
+	// the files that were walked.
+	//
+	// In the case of git, it can be assumed that the file will exist somewhere in the commit history.
```
Comment (mattyjones) [inline core/io.go:113]: I think this is fine. Never assume something though ;) If you can't prove it, then it is not real.
